# Generated by Django 4.2 on 2023-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_hamburguesa',
            field=models.CharField(choices=[('Simple', 'Hamburguesa Simple'), ('Doble', 'Hamburguesa Doble')], default='Simple', max_length=10),
        ),
    ]
