# Generated by Django 4.2 on 2023-12-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comentario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
